### ISSUE TITLE
Succesfully built SDK for 7800 XT but GPU is not useable in Hello World/pytorch

### ISSUE THREAD

**Issue by tHarvey303** [lamikr/rocm_sdk_builder#246]
I have compiled the ROCM SDK for my 7800XT, but the hello world and pytorch examples fail with different errors. I've included the outputs below, as well as other diagnostic commands used. I'm happy to provide more information if necessary. 

I'm running Ubuntu 24.04 LTS. Any assistance to get this working would be appreciated! The GPU is clearly detected, but there must be some misconfiguration or issue, but I don't know enough to fix it myself. 

Hello World:

```
tharvey@tharvey-AM5:/opt/rocm_sdk_612/docs/examples/hipcc/hello_world$ ./build.sh
rm -f ./hello_world
rm -f hello_world.o
rm -f /opt/rocm_sdk_612/src/*.o
/opt/rocm_sdk_612/bin/hipcc -g -fPIE   -c -o hello_world.o hello_world.cpp
/opt/rocm_sdk_612/bin/hipcc hello_world.o -fPIE -o hello_world
./hello_world
 System minor: 0
 System major: 11
 Agent name: AMD Radeon RX 7800 XT
Kernel input: GdkknVnqkc
Expecting that kernel increases each character from input string by one
Kernel output string: ��ξX�E>
Error, output string did not match with HelloWorld
Test failed!
make: *** [Makefile:18: test] Error 1

```

The exact kernel output changes - sometimes it is blank, or ����������

Output of pytorch hello world (jupyter notebook)

```python
import torch
print("pytorch version: " + torch.__version__)
```

    pytorch version: 2.4.1

```python
print("ROCM HIP version: " + torch.version.hip)
```

    ROCM HIP version: 6.1.40093-b69fc844c

```python
X_train = torch.FloatTensor([0., 1., 2.])
print("cuda device count: " + str(torch.cuda.device_count()))
```

    cuda device count: 2

```python
print("cuda device name: " + torch.cuda.get_device_name(0))
```

    cuda device name: AMD Radeon RX 7800 XT

```python
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print("device type: " + str(device))
```

    device type: cuda

```python
X_train = X_train.to(device)
print("Tensor training running on cuda: " + str(X_train.is_cuda))
```

    Tensor training running on cuda: True

```python
print("running simple model training test")
print(str(X_train))
```

    running simple model training test

    ---------------------------------------------------------------------------

    RuntimeError                              Traceback (most recent call last)

    Cell In[7], line 2
          1 print("running simple model training test")
    ----> 2 print(str(X_train))

    File /opt/rocm_sdk_612/lib/python3.11/site-packages/torch/_tensor.py:463, in Tensor.__repr__(self, tensor_contents)
        459     return handle_torch_function(
        460         Tensor.__repr__, (self,), self, tensor_contents=tensor_contents
        461     )
        462 # All strings are unicode in Python 3.
    --> 463 return torch._tensor_str._str(self, tensor_contents=tensor_contents)

    File /opt/rocm_sdk_612/lib/python3.11/site-packages/torch/_tensor_str.py:698, in _str(self, tensor_contents)
        696 with torch.no_grad(), torch.utils._python_dispatch._disable_current_modes():
        697     guard = torch._C._DisableFuncTorch()
    --> 698     return _str_intern(self, tensor_contents=tensor_contents)

    File /opt/rocm_sdk_612/lib/python3.11/site-packages/torch/_tensor_str.py:618, in _str_intern(inp, tensor_contents)
        616                     tensor_str = _tensor_str(self.to_dense(), indent)
        617                 else:
    --> 618                     tensor_str = _tensor_str(self, indent)
        620 if self.layout != torch.strided:
        621     suffixes.append("layout=" + str(self.layout))

    File /opt/rocm_sdk_612/lib/python3.11/site-packages/torch/_tensor_str.py:350, in _tensor_str(self, indent)
        346     return _tensor_str_with_formatter(
        347         self, indent, summarize, real_formatter, imag_formatter
        348     )
        349 else:
    --> 350     formatter = _Formatter(get_summarized_data(self) if summarize else self)
        351     return _tensor_str_with_formatter(self, indent, summarize, formatter)

    File /opt/rocm_sdk_612/lib/python3.11/site-packages/torch/_tensor_str.py:139, in _Formatter.__init__(self, tensor)
        135         self.max_width = max(self.max_width, len(value_str))
        137 else:
        138     nonzero_finite_vals = torch.masked_select(
    --> 139         tensor_view, torch.isfinite(tensor_view) & tensor_view.ne(0)
        140     )
        142     if nonzero_finite_vals.numel() == 0:
        143         # no valid number, do nothing
        144         return

    RuntimeError: HIP error: invalid device function
    HIP kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
    For debugging consider passing AMD_SERIALIZE_KERNEL=3
    Compile with `TORCH_USE_HIP_DSA` to enable device-side assertions.

```python

```

Final output of ./babs.sh -b
```
... 
BINFO_APP_SRC_SUBDIR_BASENAME: 
BINFO_APP_SRC_TOPDIR_BASENAME: DeepSpeed
BINFO_APP_SRC_DIR: /home/tharvey/work/rocm_sdk_builder/src_projects/DeepSpeed
BINFO_APP_SRC_CLONE_DIR: /home/tharvey/work/rocm_sdk_builder/src_projects/DeepSpeed
BINFO_APP_BUILD_DIR: /home/tharvey/work/rocm_sdk_builder/builddir/040_02_onnxruntime_deepspeed
HIP_PATH: /opt/rocm_sdk_612
INSTALL_DIR: /opt/rocm_sdk_612
HIP_PLATFORM: amd
TASK_RESULT_FILE_INSTALL: /home/tharvey/work/rocm_sdk_builder/builddir/040_02_onnxruntime_deepspeed/.result_install
---------------------------

LIST_BINFO_FILE_FULLNAME[91]: /home/tharvey/work/rocm_sdk_builder/binfo/core/042_python_apps_extra.binfo
APP_INFO_FULL_NAME: /home/tharvey/work/rocm_sdk_builder/binfo/core/042_python_apps_extra.binfo

---------------------------
[91] BINFO_APP_NAME: python_apps_extra
BINFO FILE: /home/tharvey/work/rocm_sdk_builder/binfo/core/042_python_apps_extra.binfo
BINFO_APP_SRC_SUBDIR_BASENAME: 
BINFO_APP_SRC_TOPDIR_BASENAME: python_apps_extra
BINFO_APP_SRC_DIR: /home/tharvey/work/rocm_sdk_builder/src_projects/python_apps_extra
BINFO_APP_SRC_CLONE_DIR: /home/tharvey/work/rocm_sdk_builder/src_projects/python_apps_extra
BINFO_APP_BUILD_DIR: /home/tharvey/work/rocm_sdk_builder/builddir/042_python_apps_extra
HIP_PATH: /opt/rocm_sdk_612
INSTALL_DIR: /opt/rocm_sdk_612
HIP_PLATFORM: amd
TASK_RESULT_FILE_INSTALL: /home/tharvey/work/rocm_sdk_builder/builddir/042_python_apps_extra/.result_install
---------------------------


ROCM SDK build and install ready
You can use following commands to check your GPU

    source /opt/rocm_sdk_612/bin/env_rocm.sh
    rocminfo

```

Output of rocminfo
```

ROCk module is loaded
=====================    
HSA System Attributes    
=====================    
Runtime Version:         1.1
Runtime Ext Version:     1.4
System Timestamp Freq.:  1000.000000MHz
Sig. Max Wait Duration:  18446744073709551615 (0xFFFFFFFFFFFFFFFF) (timestamp count)
Machine Model:           LARGE                              
System Endianness:       LITTLE                             
Mwaitx:                  DISABLED
DMAbuf Support:          YES

==========               
HSA Agents               
==========               
*******                  
Agent 1                  
*******                  
  Name:                    AMD Ryzen 7 7800X3D 8-Core Processor
  Uuid:                    CPU-XX                             
  Marketing Name:          AMD Ryzen 7 7800X3D 8-Core Processor
  Vendor Name:             CPU                                
  Feature:                 None specified                     
  Profile:                 FULL_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        0(0x0)                             
  Queue Min Size:          0(0x0)                             
  Queue Max Size:          0(0x0)                             
  Queue Type:              MULTI                              
  Node:                    0                                  
  Device Type:             CPU                                
  Cache Info:              
    L1:                      32768(0x8000) KB                   
  Chip ID:                 0(0x0)                             
  ASIC Revision:           0(0x0)                             
  Cacheline Size:          64(0x40)                           
  Max Clock Freq. (MHz):   5050                               
  BDFID:                   0                                  
  Internal Node ID:        0                                  
  Compute Unit:            16                                 
  SIMDs per CU:            0                                  
  Shader Engines:          0                                  
  Shader Arrs. per Eng.:   0                                  
  WatchPts on Addr. Ranges:1                                  
  Features:                None
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: FINE GRAINED        
      Size:                    64962816(0x3df4100) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 2                   
      Segment:                 GLOBAL; FLAGS: KERNARG, FINE GRAINED
      Size:                    64962816(0x3df4100) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 3                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    64962816(0x3df4100) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
  ISA Info:                
*******                  
Agent 2                  
*******                  
  Name:                    gfx1101                            
  Uuid:                    GPU-47334274d4b6e909               
  Marketing Name:          AMD Radeon RX 7800 XT              
  Vendor Name:             AMD                                
  Feature:                 KERNEL_DISPATCH                    
  Profile:                 BASE_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        128(0x80)                          
  Queue Min Size:          64(0x40)                           
  Queue Max Size:          131072(0x20000)                    
  Queue Type:              MULTI                              
  Node:                    1                                  
  Device Type:             GPU                                
  Cache Info:              
    L1:                      32(0x20) KB                        
    L2:                      4096(0x1000) KB                    
    L3:                      65536(0x10000) KB                  
  Chip ID:                 29822(0x747e)                      
  ASIC Revision:           0(0x0)                             
  Cacheline Size:          64(0x40)                           
  Max Clock Freq. (MHz):   2254                               
  BDFID:                   768                                
  Internal Node ID:        1                                  
  Compute Unit:            60                                 
  SIMDs per CU:            2                                  
  Shader Engines:          3                                  
  Shader Arrs. per Eng.:   2                                  
  WatchPts on Addr. Ranges:4                                  
  Coherent Host Access:    FALSE                              
  Features:                KERNEL_DISPATCH 
  Fast F16 Operation:      TRUE                               
  Wavefront Size:          32(0x20)                           
  Workgroup Max Size:      1024(0x400)                        
  Workgroup Max Size per Dimension:
    x                        1024(0x400)                        
    y                        1024(0x400)                        
    z                        1024(0x400)                        
  Max Waves Per CU:        32(0x20)                           
  Max Work-item Per CU:    1024(0x400)                        
  Grid Max Size:           4294967295(0xffffffff)             
  Grid Max Size per Dimension:
    x                        4294967295(0xffffffff)             
    y                        4294967295(0xffffffff)             
    z                        4294967295(0xffffffff)             
  Max fbarriers/Workgrp:   32                                 
  Packet Processor uCode:: 550                                
  SDMA engine uCode::      21                                 
  IOMMU Support::          None                               
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    16760832(0xffc000) KB              
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:2048KB                             
      Alloc Alignment:         4KB                                
      Accessible by all:       FALSE                              
    Pool 2                   
      Segment:                 GLOBAL; FLAGS: EXTENDED FINE GRAINED
      Size:                    16760832(0xffc000) KB              
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:2048KB                             
      Alloc Alignment:         4KB                                
      Accessible by all:       FALSE                              
    Pool 3                   
      Segment:                 GROUP                              
      Size:                    64(0x40) KB                        
      Allocatable:             FALSE                              
      Alloc Granule:           0KB                                
      Alloc Recommended Granule:0KB                                
      Alloc Alignment:         0KB                                
      Accessible by all:       FALSE                              
  ISA Info:                
    ISA 1                    
      Name:                    amdgcn-amd-amdhsa--gfx1101         
      Machine Models:          HSA_MACHINE_MODEL_LARGE            
      Profiles:                HSA_PROFILE_BASE                   
      Default Rounding Mode:   NEAR                               
      Default Rounding Mode:   NEAR                               
      Fast f16:                TRUE                               
      Workgroup Max Size:      1024(0x400)                        
      Workgroup Max Size per Dimension:
        x                        1024(0x400)                        
        y                        1024(0x400)                        
        z                        1024(0x400)                        
      Grid Max Size:           4294967295(0xffffffff)             
      Grid Max Size per Dimension:
        x                        4294967295(0xffffffff)             
        y                        4294967295(0xffffffff)             
        z                        4294967295(0xffffffff)             
      FBarrier Max Size:       32                                 
*******                  
Agent 3                  
*******                  
  Name:                    gfx1036                            
  Uuid:                    GPU-XX                             
  Marketing Name:          AMD Radeon Graphics                
  Vendor Name:             AMD                                
  Feature:                 KERNEL_DISPATCH                    
  Profile:                 BASE_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        128(0x80)                          
  Queue Min Size:          64(0x40)                           
  Queue Max Size:          131072(0x20000)                    
  Queue Type:              MULTI                              
  Node:                    2                                  
  Device Type:             GPU                                
  Cache Info:              
    L1:                      16(0x10) KB                        
    L2:                      256(0x100) KB                      
  Chip ID:                 5710(0x164e)                       
  ASIC Revision:           1(0x1)                             
  Cacheline Size:          64(0x40)                           
  Max Clock Freq. (MHz):   2200                               
  BDFID:                   4864                               
  Internal Node ID:        2                                  
  Compute Unit:            2                                  
  SIMDs per CU:            2                                  
  Shader Engines:          1                                  
  Shader Arrs. per Eng.:   1                                  
  WatchPts on Addr. Ranges:4                                  
  Coherent Host Access:    FALSE                              
  Features:                KERNEL_DISPATCH 
  Fast F16 Operation:      TRUE                               
  Wavefront Size:          32(0x20)                           
  Workgroup Max Size:      1024(0x400)                        
  Workgroup Max Size per Dimension:
    x                        1024(0x400)                        
    y                        1024(0x400)                        
    z                        1024(0x400)                        
  Max Waves Per CU:        32(0x20)                           
  Max Work-item Per CU:    1024(0x400)                        
  Grid Max Size:           4294967295(0xffffffff)             
  Grid Max Size per Dimension:
    x                        4294967295(0xffffffff)             
    y                        4294967295(0xffffffff)             
    z                        4294967295(0xffffffff)             
  Max fbarriers/Workgrp:   32                                 
  Packet Processor uCode:: 20                                 
  SDMA engine uCode::      9                                  
  IOMMU Support::          None                               
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    32481408(0x1efa080) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:2048KB                             
      Alloc Alignment:         4KB                                
      Accessible by all:       FALSE                              
    Pool 2                   
      Segment:                 GLOBAL; FLAGS: EXTENDED FINE GRAINED
      Size:                    32481408(0x1efa080) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:2048KB                             
      Alloc Alignment:         4KB                                
      Accessible by all:       FALSE                              
    Pool 3                   
      Segment:                 GROUP                              
      Size:                    64(0x40) KB                        
      Allocatable:             FALSE                              
      Alloc Granule:           0KB                                
      Alloc Recommended Granule:0KB                                
      Alloc Alignment:         0KB                                
      Accessible by all:       FALSE                              
  ISA Info:                
    ISA 1                    
      Name:                    amdgcn-amd-amdhsa--gfx1036         
      Machine Models:          HSA_MACHINE_MODEL_LARGE            
      Profiles:                HSA_PROFILE_BASE                   
      Default Rounding Mode:   NEAR                               
      Default Rounding Mode:   NEAR                               
      Fast f16:                TRUE                               
      Workgroup Max Size:      1024(0x400)                        
      Workgroup Max Size per Dimension:
        x                        1024(0x400)                        
        y                        1024(0x400)                        
        z                        1024(0x400)                        
      Grid Max Size:           4294967295(0xffffffff)             
      Grid Max Size per Dimension:
        x                        4294967295(0xffffffff)             
        y                        4294967295(0xffffffff)             
        z                        4294967295(0xffffffff)             
      FBarrier Max Size:       32                                 
*** Done ***             

```

Output of rocm-smi --version
ROCM-SMI version: 2.2.0+eb4c152
ROCM-SMI-LIB version: 7.2.0

**Comment by tHarvey303** [comment]
I found this issue on the AMD ROCm GitHub (https://github.com/ROCm/ROCm/issues/4208). When I run the suggested diagnostic `AMD_LOG_LEVEL=5 python3 -c "import torch; a=torch.randn(3).to('cuda'); print(a)" ` 

The output is  attached as a logfile (it is too big for pastebin)

[log.txt](https://github.com/user-attachments/files/19734943/log.txt)

Here is a random snippet: 
```

:1:hip_fatbin.cpp           :125 : 3169195305 us: [pid:9111  tid:0x79a41865cb80] Missing CO for these ISAs - 
:1:hip_fatbin.cpp           :128 : 3169195307 us: [pid:9111  tid:0x79a41865cb80]      amdgcn-amd-amdhsa--gfx1036
:1:hip_fatbin.cpp           :128 : 3169195308 us: [pid:9111  tid:0x79a41865cb80]      amdgcn-amd-amdhsa--gfx1101
:3:hip_platform.cpp         :703 : 3169195309 us: [pid:9111  tid:0x79a41865cb80] init: Returned hipErrorNoBinaryForGpu : continue parsing remaining modules
:1:hip_fatbin.cpp           :272 : 3169195447 us: [pid:9111  tid:0x79a41865cb80] Cannot find CO in the bundle /opt/rocm_sdk_612/lib64/librocblas.so.4.1.60102 for ISA: amdgcn-amd-amdhsa--gfx1101
:1:hip_fatbin.cpp           :125 : 3169195449 us: [pid:9111  tid:0x79a41865cb80] Missing CO for these ISAs - 
:1:hip_fatbin.cpp           :128 : 3169195450 us: [pid:9111  tid:0x79a41865cb80]      amdgcn-amd-amdhsa--gfx1036
:1:hip_fatbin.cpp           :128 : 3169195452 us: [pid:9111  tid:0x79a41865cb80]      amdgcn-amd-amdhsa--gfx1101
:3:hip_platform.cpp         :703 : 3169195453 us: [pid:9111  tid:0x79a41865cb80] init: Returned hipErrorNoBinaryForGpu : continue parsing remaining modules
:1:hip_fatbin.cpp           :272 : 3169195761 us: [pid:9111  tid:0x79a41865cb80] Cannot find CO in the bundle /opt/rocm_sdk_612/lib/python3.11/site-packages/torch/lib/libtorch_hip.so for ISA: amdgcn-amd-amdhsa--gfx1101
:1:hip_fatbin.cpp           :125 : 3169195764 us: [pid:9111  tid:0x79a41865cb80] Missing CO for these ISAs - 
:1:hip_fatbin.cpp           :128 : 3169195765 us: [pid:9111  tid:0x79a41865cb80]      amdgcn-amd-amdhsa--gfx1036
:1:hip_fatbin.cpp           :128 : 3169195766 us: [pid:9111  tid:0x79a41865cb80]      amdgcn-amd-amdhsa--gfx1101
:3:hip_platform.cpp         :703 : 3169195768 us: [pid:9111  tid:0x79a41865cb80] init: Returned hipErrorNoBinaryForGpu : continue parsing remaining modules
:1:hip_fatbin.cpp           :272 : 3169195925 us: [pid:9111  tid:0x79a41865cb80] Cannot find CO in the bundle /opt/rocm_sdk_612/lib/libmagma.so for ISA: amdgcn-amd-amdhsa--gfx1101
:1:hip_fatbin.cpp           :125 : 3169195927 us: [pid:9111  tid:0x79a41865cb80] Missing CO for these ISAs - 
:1:hip_fatbin.cpp           :128 : 3169195929 us: [pid:9111  tid:0x79a41865cb80]      amdgcn-amd-amdhsa--gfx1036
:1:hip_fatbin.cpp           :128 : 3169195930 us: [pid:9111  tid:0x79a41865cb80]      amdgcn-amd-amdhsa--gfx1101
:3:hip_platform.cpp         :703 : 3169195932 us: [pid:9111  tid:0x79a41865cb80] init: Returned hipErrorNoBinaryForGpu : continue parsing remaining modules
:1:hip_fatbin.cpp           :272 : 3169196068 us: [pid:9111  tid:0x79a41865cb80] Cannot find CO in the bundle /opt/rocm_sdk_612/lib64/librocsolver.so.0.1.60102 for ISA: amdgcn-amd-amdhsa--gfx1101
:1:hip_fatbin.cpp           :125 : 3169196071 us: [pid:9111  tid:0x79a41865cb80] Missing CO for these ISAs - 
:1:hip_fatbin.cpp           :128 : 3169196072 us: [pid:9111  tid:0x79a41865cb80]      amdgcn-amd-amdhsa--gfx1036
:1:hip_fatbin.cpp           :128 : 3169196073 us: [pid:9111  tid:0x79a41865cb80]      amdgcn-amd-amdhsa--gfx1101
:3:hip_platform.cpp         :703 : 3169196075 us: [pid:9111  tid:0x79a41865cb80] init: Returned hipErrorNoBinaryForGpu : continue parsing remaining modules
:1:hip_fatbin.cpp           :272 : 3169196184 us: [pid:9111  tid:0x79a41865cb80] Cannot find CO in the bundle /opt/rocm_sdk_612/lib64/librocsparse.so.1.0.60102 for ISA: amdgcn-amd-amdhsa--gfx1101
:1:hip_fatbin.cpp           :125 : 3169196188 us: [pid:9111  tid:0x79a41865cb80] Missing CO for these ISAs - 
:1:hip_fatbin.cpp           :128 : 3169196190 us: [pid:9111  tid:0x79a41865cb80]      amdgcn-amd-amdhsa--gfx1036
:1:hip_fatbin.cpp           :128 : 3169196191 us: [pid:9111  tid:0x79a41865cb80]      amdgcn-amd-amdhsa--gfx1101
:3:hip_platform.cpp         :703 : 3169196192 us: [pid:9111  tid:0x79a41865cb80] init: Returned hipErrorNoBinaryForGpu : continue parsing remaining modules
:1:hip_fatbin.cpp           :272 : 3169196502 us: [pid:9111  tid:0x79a41865cb80] Cannot find CO in the bundle /opt/rocm_sdk_612/lib/python3.11/site-packages/torch/lib/libtorch_hip.so for ISA: amdgcn-amd-amdhsa--gfx1101
:1:hip_fatbin.cpp           :125 : 3169196504 us: [pid:9111  tid:0x79a41865cb80] Missing CO for these ISAs - 
:1:hip_fatbin.cpp           :128 : 3169196505 us: [pid:9111  tid:0x79a41865cb80]      amdgcn-amd-amdhsa--gfx1036
:1:hip_fatbin.cpp           :128 : 3169196506 us: [pid:9111  tid:0x79a41865cb80]      amdgcn-amd-amdhsa--gfx1101
:3:hip_platform.cpp         :703 : 3169196508 us: [pid:9111  tid:0x79a41865cb80] init: Returned hipErrorNoBinaryForGpu : continue parsing remaining modules
:1:hip_fatbin.cpp           :272 : 3169196666 us: [pid:9111  tid:0x79a41865cb80] Cannot find CO in the bundle /opt/rocm_sdk_612/lib/libmagma.so for ISA: amdgcn-amd-amdhsa--gfx1101
:1:hip_fatbin.cpp           :125 : 3169196668 us: [pid:9111  tid:0x79a41865cb80] Missing CO for these ISAs - 
:1:hip_fatbin.cpp           :128 : 3169196669 us: [pid:9111  tid:0x79a41865cb80]      amdgcn-amd-amdhsa--gfx1036
:1:hip_fatbin.cpp           :128 : 3169196670 us: [pid:9111  tid:0x79a41865cb80]      amdgcn-amd-amdhsa--gfx1101
:3:hip_platform.cpp         :703 : 3169196672 us: [pid:9111  tid:0x79a41865cb80] init: Returned hipErrorNoBinaryForGpu : continue parsing remaining modules
:1:hip_fatbin.cpp           :272 : 3169196830 us: [pid:9111  tid:0x79a41865cb80] Cannot find CO in the bundle /opt/rocm_sdk_612/lib/libmagma.so for ISA: amdgcn-amd-amdhsa--gfx1101
:1:hip_fatbin.cpp           :125 : 3169196832 us: [pid:9111  tid:0x79a41865cb80] Missing CO for these ISAs - 
:1:hip_fatbin.cpp           :128 : 3169196833 us: [pid:9111  tid:0x79a41865cb80]      amdgcn-amd-amdhsa--gfx1036
:1:hip_fatbin.cpp           :128 : 3169196834 us: [pid:9111  tid:0x79a41865cb80]      amdgcn-amd-amdhsa--gfx1101
:3:hip_platform.cpp         :703 : 3169196836 us: [pid:9111  tid:0x79a41865cb80] init: Returned hipErrorNoBinaryForGpu : continue parsing remaining modules
:1:hip_fatbin.cpp           :272 : 3169196994 us: [pid:9111  tid:0x79a41865cb80] Cannot find CO in the bundle /opt/rocm_sdk_612/lib/libmagma.so for ISA: amdgcn-amd-amdhsa--gfx1101
:1:hip_fatbin.cpp           :125 : 3169196996 us: [pid:9111  tid:0x79a41865cb80] Missing CO for these ISAs - 
:1:hip_fatbin.cpp           :128 : 3169196997 us: [pid:9111  tid:0x79a41865cb80]      amdgcn-amd-amdhsa--gfx1036
:1:hip_fatbin.cpp           :128 : 3169196999 us: [pid:9111  tid:0x79a41865cb80]      amdgcn-amd-amdhsa--gfx1101
:3:hip_platform.cpp         :703 : 3169197001 us: [pid:9111  tid:0x79a41865cb80] init: Returned hipErrorNoBinaryForGpu : continue parsing remaining modules
:1:hip_fatbin.cpp           :272 : 3169197164 us: [pid:9111  tid:0x79a41865cb80] Cannot find CO in the bundle /opt/rocm_sdk_612/lib/libmagma.so for ISA: amdgcn-amd-amdhsa--gfx1101
:1:hip_fatbin.cpp           :125 : 3169197168 us: [pid:9111  tid:0x79a41865cb80] Missing CO for these ISAs - 
:1:hip_fatbin.cpp           :128 : 3169197170 us: [pid:9111  tid:0x79a41865cb80]      amdgcn-amd-amdhsa--gfx1036
:1:hip_fatbin.cpp           :128 : 3169197171 us: [pid:9111  tid:0x79a41865cb80]      amdgcn-amd-amdhsa--gfx1101
:3:hip_platform.cpp         :703 : 3169197173 us: [pid:9111  tid:0x79a41865cb80] init: Returned hipErrorNoBinaryForGpu : continue parsing remaining modules
:1:hip_fatbin.cpp           :272 : 3169197478 us: [pid:9111  tid:0x79a41865cb80] Cannot find CO in the bundle /opt/rocm_sdk_612/lib/python3.11/site-packages/torch/lib/libtorch_hip.so for ISA: amdgcn-amd-amdhsa--gfx1101
:1:hip_fatbin.cpp           :125 : 3169197482 us: [pid:9111  tid:0x79a41865cb80] Missing CO for these ISAs - 
:1:hip_fatbin.cpp           :128 : 3169197484 us: [pid:9111  tid:0x79a41865cb80]      amdgcn-amd-amdhsa--gfx1036
:1:hip_fatbin.cpp           :128 : 3169197485 us: [pid:9111  tid:0x79a41865cb80]      amdgcn-amd-amdhsa--gfx1101
:3:hip_platform.cpp         :703 : 3169197487 us: [pid:9111  tid:0x79a41865cb80] init: Returned hipErrorNoBinaryForGpu : continue parsing remaining modules
:1:hip_fatbin.cpp           :272 : 3169197643 us: [pid:9111  tid:0x79a41865cb80] Cannot find CO in the bundle /opt/rocm_sdk_612/lib/libmagma.so for ISA: amdgcn-amd-amdhsa--gfx1101
:1:hip_fatbin.cpp           :125 : 3169197646 us: [pid:9111  tid:0x79a41865cb80] Missing CO for these ISAs - 
:1:hip_fatbin.cpp           :128 : 3169197647 us: [pid:9111  tid:0x79a41865cb80]      amdgcn-amd-amdhsa--gfx1036
:1:hip_fatbin.cpp           :128 : 3169197648 us: [pid:9111  tid:0x79a41865cb80]      amdgcn-amd-amdhsa--gfx1101
:3:hip_platform.cpp         :703 : 3169197650 us: [pid:9111  tid:0x79a41865cb80] init: Returned hipErrorNoBinaryForGpu : continue parsing remaining modules
:1:hip_fatbin.cpp           :272 : 3169197955 us: [pid:9111  tid:0x79a41865cb80] Cannot find CO in the bundle /opt/rocm_sdk_612/lib/python3.11/site-packages/torch/lib/libtorch_hip.so for ISA: amdgcn-amd-amdhsa--gfx1101
:1:hip_fatbin.cpp           :125 : 3169197957 us: [pid:9111  tid:0x79a41865cb80] Missing CO for these ISAs - 
:1:hip_fatbin.cpp           :128 : 3169197959 us: [pid:9111  tid:0x79a41865cb80]      amdgcn-amd-amdhsa--gfx1036
:1:hip_fatbin.cpp           :128 : 3169197960 us: [pid:9111  tid:0x79a41865cb80]      amdgcn-amd-amdhsa--gfx1101
:3:hip_platform.cpp         :703 : 3169197961 us: [pid:9111  tid:0x79a41865cb80] init: Returned hipErrorNoBinaryForGpu : continue parsing remaining modules
:3:hip_platform.cpp         :703 : 3169388632 us: [pid:9111  tid:0x79a41865cb80] init: Returned hipErrorNoBinaryForGpu : continue parsing remaining modules
:1:hip_fatbin.cpp           :272 : 3169388933 us: [pid:9111  tid:0x79a41865cb80] Cannot find CO in the bundle /opt/rocm_sdk_612/lib/python3.11/site-packages/torch/lib/libtorch_hip.so for ISA: amdgcn-amd-amdhsa--gfx1101
:1:hip_fatbin.cpp           :125 : 3169388935 us: [pid:9111  tid:0x79a41865cb80] Missing CO for these ISAs - 
:1:hip_fatbin.cpp           :128 : 3169388937 us: [pid:9111  tid:0x79a41865cb80]      amdgcn-amd-amdhsa--gfx1036
:1:hip_fatbin.cpp           :128 : 3169388938 us: [pid:9111  tid:0x79a41865cb80]      amdgcn-amd-amdhsa--gfx1101
:3:hip_platform.cpp         :703 : 3169388939 us: [pid:9111  tid:0x79a41865cb80] init: Returned hipErrorNoBinaryForGpu : continue parsing remaining modules
:1:hip_fatbin.cpp           :272 : 3169389245 us: [pid:9111  tid:0x79a41865cb80] Cannot find CO in the bundle /opt/rocm_sdk_612/lib/python3.11/site-packages/torch/lib/libtorch_hip.so for ISA: amdgcn-amd-amdhsa--gfx1101
:1:hip_fatbin.cpp           :125 : 3169389249 us: [pid:9111  tid:0x79a41865cb80] Missing CO for these ISAs - 
:1:hip_fatbin.cpp           :128 : 3169389250 us: [pid:9111  tid:0x79a41865cb80]      amdgcn-amd-amdhsa--gfx1036
:1:hip_fatbin.cpp           :128 : 3169389251 us: [pid:9111  tid:0x79a41865cb80]      amdgcn-amd-amdhsa--gfx1101
:3:hip_platform.cpp         :703 : 3169389253 us: [pid:9111  tid:0x79a41865cb80] init: Returned hipErrorNoBinaryForGpu : continue parsing remaining modules
:3:hip_device_runtime.cpp   :638 : 3169392699 us: [pid:9111  tid:0x79a41865cb80] [32m hipGetDeviceCount ( 0x7fff42656660 ) [0m
:3:hip_device_runtime.cpp   :640 : 3169392704 us: [pid:9111  tid:0x79a41865cb80] hipGetDeviceCount: Returned hipSuccess : 
:3:hip_device_runtime.cpp   :638 : 3169392718 us: [pid:9111  tid:0x79a41865cb80] [32m hipGetDeviceCount ( 0x79a3c49833f4 ) [0m
:3:hip_device_runtime.cpp   :640 : 3169392720 us: [pid:9111  tid:0x79a41865cb80] hipGetDeviceCount: Returned hipSuccess : 
:3:hip_device.cpp           :471 : 3169392724 us: [pid:9111  tid:0x79a41865cb80] [32m hipGetDevicePropertiesR0600 ( 0x7fff42656188, 0 ) [0m
:3:hip_device.cpp           :473 : 3169392726 us: [pid:9111  tid:0x79a41865cb80] hipGetDevicePropertiesR0600: Returned hipSuccess : 
:3:hip_device.cpp           :471 : 3169392729 us: [pid:9111  tid:0x79a41865cb80] [32m hipGetDevicePropertiesR0600 ( 0x7fff42656188, 1 ) [0m
:3:hip_device.cpp           :473 : 3169392731 us: [pid:9111  tid:0x79a41865cb80] hipGetDevicePropertiesR0600: Returned hipSuccess : 
:3:hip_device_runtime.cpp   :638 : 3169392738 us: [pid:9111  tid:0x79a41865cb80] [32m hipGetDeviceCount ( 0x7fff42656698 ) [0m
:3:hip_device_runtime.cpp   :640 : 3169392740 us: [pid:9111  tid:0x79a41865cb80] hipGetDeviceCount: Returned hipSuccess : 
:3:hip_device_runtime.cpp   :623 : 3169392749 us: [pid:9111  tid:0x79a41865cb80] [32m hipGetDevice ( 0x7fff4265628c ) [0m
:3:hip_device_runtime.cpp   :631 : 3169392751 us: [pid:9111  tid:0x79a41865cb80] hipGetDevice: Returned hipSuccess : 
:3:hip_device_runtime.cpp   :638 : 3169392753 us: [pid:9111  tid:0x79a41865cb80] [32m hipGetDeviceCount ( 0x7fff426561d4 ) [0m
:3:hip_device_runtime.cpp   :640 : 3169392755 us: [pid:9111  tid:0x79a41865cb80] hipGetDeviceCount: Returned hipSuccess : 
:3:hip_context.cpp          :340 : 3169392883 us: [pid:9111  tid:0x79a41865cb80] [32m hipDevicePrimaryCtxGetState ( 0, 0x7fff42656288, 0x7fff4265628c ) [0m
:3:hip_context.cpp          :354 : 3169392886 us: [pid:9111  tid:0x79a41865cb80] hipDevicePrimaryCtxGetState: Returned hipSuccess : 
:3:hip_device_runtime.cpp   :623 : 3169392889 us: [pid:9111  tid:0x79a41865cb80] [32m hipGetDevice ( 0x7fff426562ac ) [0m
:3:hip_device_runtime.cpp   :631 : 3169392891 us: [pid:9111  tid:0x79a41865cb80] hipGetDevice: Returned hipSuccess : 
:3:hip_context.cpp          :340 : 3169392893 us: [pid:9111  tid:0x79a41865cb80] [32m hipDevicePrimaryCtxGetState ( 0, 0x7fff426562a8, 0x7fff426562ac ) [0m
:3:hip_context.cpp          :354 : 3169392895 us: [pid:9111  tid:0x79a41865cb80] hipDevicePrimaryCtxGetState: Returned hipSuccess : 
:3:hip_device_runtime.cpp   :623 : 3169392913 us: [pid:9111  tid:0x79a41865cb80] [32m hipGetDevice ( 0x7fff4265624c ) [0m
:3:hip_device_runtime.cpp   :631 : 3169392915 us: [pid:9111  tid:0x79a41865cb80] hipGetDevice: Returned hipSuccess : 
:3:hip_context.cpp          :340 : 3169392917 us: [pid:9111  tid:0x79a41865cb80] [32m hipDevicePrimaryCtxGetState ( 0, 0x7fff42656248, 0x7fff4265624c ) [0m
:3:hip_context.cpp          :354 : 3169392919 us: [pid:9111  tid:0x79a41865cb80] hipDevicePrimaryCtxGetState: Returned hipSuccess : 
:3:hip_device_runtime.cpp   :623 : 3169392922 us: [pid:9111  tid:0x79a41865cb80] [32m hipGetDevice ( 0x7fff4265628c ) [0m
:3:hip_device_runtime.cpp   :631 : 3169392923 us: [pid:9111  tid:0x79a41865cb80] hipGetDevice: Returned hipSuccess : 
:3:hip_context.cpp          :340 : 3169392925 us: [pid:9111  tid:0x79a41865cb80] [32m hipDevicePrimaryCtxGetState ( 0, 0x7fff42656288, 0x7fff4265628c ) [0m
:3:hip_context.cpp          :354 : 3169392927 us: [pid:9111  tid:0x79a41865cb80] hipDevicePrimaryCtxGetState: Returned hipSuccess : 
:3:hip_device_runtime.cpp   :623 : 3169392929 us: [pid:9111  tid:0x79a41865cb80] [32m hipGetDevice ( 0x7fff426562ac ) [0m
:3:hip_device_runtime.cpp   :631 : 3169392930 us: [pid:9111  tid:0x79a41865cb80] hipGetDevice: Returned hipSuccess : 
:3:hip_context.cpp          :340 : 3169392932 us: [pid:9111  tid:0x79a41865cb80] [32m hipDevicePrimaryCtxGetState ( 0, 0x7fff426562a8, 0x7fff426562ac ) [0m
:3:hip_context.cpp          :354 : 3169392934 us: [pid:9111  tid:0x79a41865cb80] hipDevicePrimaryCtxGetState: Returned hipSuccess : 
:3:hip_device_runtime.cpp   :623 : 3169392952 us: [pid:9111  tid:0x79a41865cb80] [32m hipGetDevice ( 0x7fff4265624c ) [0m
:3:hip_device_runtime.cpp   :631 : 3169392953 us: [pid:9111  tid:0x79a41865cb80] hipGetDevice: Returned hipSuccess : 
:3:hip_context.cpp          :340 : 3169392955 us: [pid:9111  tid:0x79a41865cb80] [32m hipDevicePrimaryCtxGetState ( 0, 0x7fff42656248, 0x7fff4265624c ) [0m
:3:hip_context.cpp          :354 : 3169392957 us: [pid:9111  tid:0x79a41865cb80] hipDevicePrimaryCtxGetState: Returned hipSuccess : 
:3:hip_device_runtime.cpp   :623 : 3169393197 us: [pid:9111  tid:0x79a41865cb80] [32m hipGetDevice ( 0x7fff42656974 ) [0m
:3:hip_device_runtime.cpp   :631 : 3169393203 us: [pid:9111  tid:0x79a41865cb80] hipGetDevice: Returned hipSuccess : 
:3:hip_device_runtime.cpp   :623 : 3169393237 us: [pid:9111  tid:0x79a41865cb80] [32m hipGetDevice ( 0x7fff42655b54 ) [0m
:3:hip_device_runtime.cpp   :631 : 3169393238 us: [pid:9111  tid:0x79a41865cb80] hipGetDevice: Returned hipSuccess : 
:3:hip_device_runtime.cpp   :623 : 3169393241 us: [pid:9111  tid:0x79a41865cb80] [32m hipGetDevice ( 0x7fff42655a34 ) [0m
:3:hip_device_runtime.cpp   :631 : 3169393245 us: [pid:9111  tid:0x79a41865cb80] hipGetDevice: Returned hipSuccess : 
:3:hip_device_runtime.cpp   :623 : 3169393251 us: [pid:9111  tid:0x79a41865cb80] [32m hipGetDevice ( 0x7fff426557ec ) [0m
:3:hip_device_runtime.cpp   :631 : 3169393253 us: [pid:9111  tid:0x79a41865cb80] hipGetDevice: Returned hipSuccess : 
:3:hip_stream.cpp           :395 : 3169393258 us: [pid:9111  tid:0x79a41865cb80] [32m hipDeviceGetStreamPriorityRange ( 0x7fff42655798, 0x7fff4265579c ) [0m
:3:hip_stream.cpp           :403 : 3169393260 us: [pid:9111  tid:0x79a41865cb80] hipDeviceGetStreamPriorityRange: Returned hipSuccess : 
:3:hip_error.cpp            :36  : 3169393268 us: [pid:9111  tid:0x79a41865cb80] [32m hipGetLastError (  ) [0m
:3:hip_device_runtime.cpp   :623 : 3169393270 us: [pid:9111  tid:0x79a41865cb80] [32m hipGetDevice ( 0x7fff4265500c ) [0m
:3:hip_device_runtime.cpp   :631 : 3169393271 us: [pid:9111  tid:0x79a41865cb80] hipGetDevice: Returned hipSuccess : 
:3:hip_graph.cpp            :826 : 3169393276 us: [pid:9111  tid:0x79a41865cb80] [32m hipStreamIsCapturing ( stream:<null>, 0x7fff42655238 ) [0m
:3:hip_graph.cpp            :827 : 3169393279 us: [pid:9111  tid:0x79a41865cb80] hipStreamIsCapturing: Returned hipSuccess : 
:3:hip_memory.cpp           :599 : 3169393290 us: [pid:9111  tid:0x79a41865cb80] [32m hipMalloc ( 0x7fff42655348, 2097152 ) [0m
:4:rocdevice.cpp            :2324: 3169393323 us: [pid:9111  tid:0x79a41865cb80] Allocate hsa device memory 0x79a1e9400000, size 0x200000
:3:rocdevice.cpp            :2363: 3169393326 us: [pid:9111  tid:0x79a41865cb80] device=0x648bf5828d90, freeMem_ = 0x3fee00000
:3:hip_memory.cpp           :601 : 3169393328 us: [pid:9111  tid:0x79a41865cb80] hipMalloc: Returned hipSuccess : 0x79a1e9400000: duration: 38 us
:3:hip_device_runtime.cpp   :653 : 3169393335 us: [pid:9111  tid:0x79a41865cb80] [32m hipSetDevice ( 0 ) [0m
:3:hip_device_runtime.cpp   :657 : 3169393337 us: [pid:9111  tid:0x79a41865cb80] hipSetDevice: Returned hipSuccess : 
:3:hip_device_runtime.cpp   :653 : 3169393339 us: [pid:9111  tid:0x79a41865cb80] [32m hipSetDevice ( 0 ) [0m
:3:hip_device_runtime.cpp   :657 : 3169393340 us: [pid:9111  tid:0x79a41865cb80] hipSetDevice: Returned hipSuccess : 
:3:hip_device_runtime.cpp   :623 : 3169393363 us: [pid:9111  tid:0x79a41865cb80] [32m hipGetDevice ( 0x7fff42655a54 ) [0m
:3:hip_device_runtime.cpp   :631 : 3169393364 us: [pid:9111  tid:0x79a41865cb80] hipGetDevice: Returned hipSuccess : 
:3:hip_device_runtime.cpp   :623 : 3169393366 us: [pid:9111  tid:0x79a41865cb80] [32m hipGetDevice ( 0x7fff4265586c ) [0m
:3:hip_device_runtime.cpp   :631 : 3169393368 us: [pid:9111  tid:0x79a41865cb80] hipGetDevice: Returned hipSuccess : 
:3:hip_memory.cpp           :685 : 3169393377 us: [pid:9111  tid:0x79a41865cb80] [32m hipMemcpyWithStream ( 0x79a1e9400000, 0x648bf57d4540, 12, hipMemcpyHostToDevice, stream:<null> ) [0m
:3:rocdevice.cpp            :2935: 3169393383 us: [pid:9111  tid:0x79a41865cb80] number of allocated hardware queues with low priority: 0, with normal priority: 0, with high priority: 0, maximum per priority is: 4
:3:rocdevice.cpp            :3013: 3169402222 us: [pid:9111  tid:0x79a41865cb80] created hardware queue 0x79a3d5450000 with size 16384 with priority 1, cooperative: 0
:3:rocdevice.cpp            :3105: 3169402233 us: [pid:9111  tid:0x79a41865cb80] acquireQueue refCount: 0x79a3d5450000 (1)
:4:rocdevice.cpp            :2182: 3169402427 us: [pid:9111  tid:0x79a41865cb80] Allocate hsa host memory 0x79a1e8f00000, size 0x100000, numa_node = 0
:3:devprogram.cpp           :2679: 3169558362 us: [pid:9111  tid:0x79a41865cb80] Using Code Object V5.
:4:command.cpp              :346 : 3169559855 us: [pid:9111  tid:0x79a41865cb80] Command (CopyHostToDevice) enqueued: 0x648bf5ffb290
:4:rocblit.cpp              :832 : 3169560454 us: [pid:9111  tid:0x79a41865cb80] HSA Async Copy staged H2D dst=0x79a1e9400000, src=0x79a1e9d00000, size=12, completion_signal=0x79a2eb7ff700
:4:rocvirtual.cpp           :570 : 3169560463 us: [pid:9111  tid:0x79a41865cb80] Host wait on completion_signal=0x79a2eb7ff700
:3:rocvirtual.hpp           :66  : 3169560465 us: [pid:9111  tid:0x79a41865cb80] Host active wait for Signal = (0x79a2eb7ff700) for -1 ns
:4:command.cpp              :285 : 3169560557 us: [pid:9111  tid:0x79a41865cb80] Queue marker to command queue: 0x648bf5aabd20
:4:command.cpp              :346 : 3169560559 us: [pid:9111  tid:0x79a41865cb80] Command (InternalMarker) enqueued: 0x648bf617a320
:4:command.cpp              :175 : 3169560562 us: [pid:9111  tid:0x79a41865cb80] Command 0x648bf5ffb290 complete
:4:command.cpp              :169 : 3169560563 us: [pid:9111  tid:0x79a41865cb80] Command 0x648bf617a320 complete (Wall: 3169560563, CPU: 0, GPU: 0 us)
:4:command.cpp              :249 : 3169560566 us: [pid:9111  tid:0x79a41865cb80] Waiting for event 0x648bf5ffb290 to complete, current status 0
:4:command.cpp              :264 : 3169560568 us: [pid:9111  tid:0x79a41865cb80] Event 0x648bf5ffb290 wait completed
:3:hip_memory.cpp           :696 : 3169560570 us: [pid:9111  tid:0x79a41865cb80] hipMemcpyWithStream: Returned hipSuccess : : duration: 167193 us
:3:hip_device_runtime.cpp   :653 : 3169560574 us: [pid:9111  tid:0x79a41865cb80] [32m hipSetDevice ( 0 ) [0m
:3:hip_device_runtime.cpp   :657 : 3169560575 us: [pid:9111  tid:0x79a41865cb80] hipSetDevice: Returned hipSuccess : 
:3:hip_device_runtime.cpp   :623 : 3169561007 us: [pid:9111  tid:0x79a41865cb80] [32m hipGetDevice ( 0x7fff42655b44 ) [0m
:3:hip_device_runtime.cpp   :631 : 3169561017 us: [pid:9111  tid:0x79a41865cb80] hipGetDevice: Returned hipSuccess : 
:3:hip_device_runtime.cpp   :623 : 3169561020 us: [pid:9111  tid:0x79a41865cb80] [32m hipGetDevice ( 0x7fff42655a54 ) [0m
:3:hip_device_runtime.cpp   :631 : 3169561021 us: [pid:9111  tid:0x79a41865cb80] hipGetDevice: Returned hipSuccess : 
:3:hip_device_runtime.cpp   :623 : 3169561024 us: [pid:9111  tid:0x79a41865cb80] [32m hipGetDevice ( 0x7fff4265568c ) [0m
:3:hip_device_runtime.cpp   :631 : 3169561025 us: [pid:9111  tid:0x79a41865cb80] hipGetDevice: Returned hipSuccess : 
:3:hip_device_runtime.cpp   :653 : 3169561028 us: [pid:9111  tid:0x79a41865cb80] [32m hipSetDevice ( 0 ) [0m
:3:hip_device_runtime.cpp   :657 : 3169561029 us: [pid:9111  tid:0x79a41865cb80] hipSetDevice: Returned hipSuccess : 
:3:hip_device_runtime.cpp   :653 : 3169561031 us: [pid:9111  tid:0x79a41865cb80] [32m hipSetDevice ( 0 ) [0m
:3:hip_device_runtime.cpp   :657 : 3169561032 us: [pid:9111  tid:0x79a41865cb80] hipSetDevice: Returned hipSuccess : 
:3:hip_device_runtime.cpp   :623 : 3169561040 us: [pid:9111  tid:0x79a41865cb80] [32m hipGetDevice ( 0x7fff42655da4 ) [0m
:3:hip_device_runtime.cpp   :631 : 3169561041 us: [pid:9111  tid:0x79a41865cb80] hipGetDevice: Returned hipSuccess : 
:3:hip_device_runtime.cpp   :623 : 3169561061 us: [pid:9111  tid:0x79a41865cb80] [32m hipGetDevice ( 0x7fff42655450 ) [0m
:3:hip_device_runtime.cpp   :631 : 3169561062 us: [pid:9111  tid:0x79a41865cb80] hipGetDevice: Returned hipSuccess : 
:3:hip_device_runtime.cpp   :623 : 3169561064 us: [pid:9111  tid:0x79a41865cb80] [32m hipGetDevice ( 0x7fff4265514c ) [0m
:3:hip_device_runtime.cpp   :631 : 3169561065 us: [pid:9111  tid:0x79a41865cb80] hipGetDevice: Returned hipSuccess : 
:3:hip_device_runtime.cpp   :653 : 3169561069 us: [pid:9111  tid:0x79a41865cb80] [32m hipSetDevice ( 0 ) [0m
:3:hip_device_runtime.cpp   :657 : 3169561070 us: [pid:9111  tid:0x79a41865cb80] hipSetDevice: Returned hipSuccess : 
:3:hip_device_runtime.cpp   :623 : 3169561075 us: [pid:9111  tid:0x79a41865cb80] [32m hipGetDevice ( 0x7fff426554ec ) [0m
:3:hip_device_runtime.cpp   :631 : 3169561076 us: [pid:9111  tid:0x79a41865cb80] hipGetDevice: Returned hipSuccess : 
:3:hip_platform.cpp         :219 : 3169561080 us: [pid:9111  tid:0x79a41865cb80] [32m __hipPushCallConfiguration ( {1,1,1}, {256,1,1}, 0, stream:<null> ) [0m
:3:hip_platform.cpp         :223 : 3169561082 us: [pid:9111  tid:0x79a41865cb80] __hipPushCallConfiguration: Returned hipSuccess : 
:3:hip_platform.cpp         :228 : 3169561093 us: [pid:9111  tid:0x79a41865cb80] [32m __hipPopCallConfiguration ( {0,0,1}, {160489836,31140,1}, 0x7fff42655758, 0x7fff42655748 ) [0m
:3:hip_platform.cpp         :237 : 3169561096 us: [pid:9111  tid:0x79a41865cb80] __hipPopCallConfiguration: Returned hipSuccess : 
:3:hip_module.cpp           :669 : 3169561101 us: [pid:9111  tid:0x79a41865cb80] [32m hipLaunchKernel ( 0x79a40818d3a8, {1,1,1}, {256,1,1}, 0x7fff42655770, 0, stream:<null> ) [0m
:3:hip_module.cpp           :670 : 3169561104 us: [pid:9111  tid:0x79a41865cb80] hipLaunchKernel: Returned hipErrorInvalidDeviceFunction : 
:3:hip_error.cpp            :36  : 3169561107 us: [pid:9111  tid:0x79a41865cb80] [32m hipGetLastError (  ) [0m
:3:hip_error.cpp            :36  : 3169561108 us: [pid:9111  tid:0x79a41865cb80] [32m hipGetLastError (  ) [0m
:3:hip_device_runtime.cpp   :653 : 3169561293 us: [pid:9111  tid:0x79a41865cb80] [32m hipSetDevice ( 0 ) [0m
:3:hip_device_runtime.cpp   :657 : 3169561295 us: [pid:9111  tid:0x79a41865cb80] hipSetDevice: Returned hipSuccess : 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/rocm_sdk_612/lib/python3.11/site-packages/torch/_tensor.py", line 463, in __repr__
    return torch._tensor_str._str(self, tensor_contents=tensor_contents)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/rocm_sdk_612/lib/python3.11/site-packages/torch/_tensor_str.py", line 698, in _str
    return _str_intern(self, tensor_contents=tensor_contents)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/rocm_sdk_612/lib/python3.11/site-packages/torch/_tensor_str.py", line 618, in _str_intern
    tensor_str = _tensor_str(self, indent)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/rocm_sdk_612/lib/python3.11/site-packages/torch/_tensor_str.py", line 350, in _tensor_str
    formatter = _Formatter(get_summarized_data(self) if summarize else self)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/rocm_sdk_612/lib/python3.11/site-packages/torch/_tensor_str.py", line 139, in __init__
    tensor_view, torch.isfinite(tensor_view) & tensor_view.ne(0)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: HIP error: invalid device function
HIP kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing AMD_SERIALIZE_KERNEL=3
Compile with `TORCH_USE_HIP_DSA` to enable device-side assertions.

:1:hip_fatbin.cpp           :99  : 3169822293 us: [pid:9111  tid:0x79a41865cb80] All Unique FDs are closed
:1:hip_fatbin.cpp           :272 : 3169198118 us: [pid:9111  tid:0x79a41865cb80] Cannot find CO in the bundle /opt/rocm_sdk_612/lib/libmagma.so for ISA: amdgcn-amd-amdhsa--gfx1101
:1:hip_fatbin.cpp           :125 : 3169198121 us: [pid:9111  tid:0x79a41865cb80] Missing CO for these ISAs - 
:1:hip_fatbin.cpp           :128 : 3169198123 us: [pid:9111  tid:0x79a41865cb80]      amdgcn-amd-amdhsa--gfx1036
:1:hip_fatbin.cpp           :128 : 3169198124 us: [pid:9111  tid:0x79a41865cb80]      amdgcn-amd-amdhsa--gfx1101
:3:hip_platform.cpp         :703 : 3169198126 us: [pid:9111  tid:0x79a41865cb80] init: Returned hipErrorNoBinaryForGpu : continue parsing remaining modules
:1:hip_fatbin.cpp           :272 : 3169198280 us: [pid:9111  tid:0x79a41865cb80] Cannot find CO in the bundle /opt/rocm_sdk_612/lib/libmagma.so for ISA: amdgcn-amd-amdhsa--gfx1101
:1:hip_fatbin.cpp           :125 : 3169198282 us: [pid:9111  tid:0x79a41865cb80] Missing CO for these ISAs - 
:1:hip_fatbin.cpp           :128 : 3169198283 us: [pid:9111  tid:0x79a41865cb80]      amdgcn-amd-amdhsa--gfx1036
:1:hip_fatbin.cpp           :128 : 3169198285 us: [pid:9111  tid:0x79a41865cb80]      amdgcn-amd-amdhsa--gfx1101
:3:hip_platform.cpp         :703 : 3169198286 us: [pid:9111  tid:0x79a41865cb80] init: Returned hipErrorNoBinaryForGpu : continue parsing remaining modules
:1:hip_fatbin.cpp           :272 : 3169198443 us: [pid:9111  tid:0x79a41865cb80] Cannot find CO in the bundle /opt/rocm_sdk_612/lib/libmagma.so for ISA: amdgcn-amd-amdhsa--gfx1101
:1:hip_fatbin.cpp           :125 : 3169198445 us: [pid:9111  tid:0x79a41865cb80] Missing CO for these ISAs - 
:1:hip_fatbin.cpp           :128 : 3169198446 us: [pid:9111  tid:0x79a41865cb80]      amdgcn-amd-amdhsa--gfx1036
:1:hip_fatbin.cpp           :128 : 3169198447 us: [pid:9111  tid:0x79a41865cb80]      amdgcn-amd-amdhsa--gfx1101
```

Any suggestions are much appreciated! It looks like it can't find the binaries it needs for the GPU.

I've noticed as well looking at the above that it's trying to find binaries for the IGPU on my CPU, so I've set it only visible to the GPU with the ROCR_VISIBLE_DEVICES environment variable, but the error is the same as above, only it doesn't mention the gfx1036 anymore.

**Comment by tHarvey303** [comment]
Ok, after much messing around I got it to work. Originally it was compiled for gfx1100, not gfx1101, so I recompiled for gfx1101, but there were a number of crashes in installing different components which I had to overcome manually. It would be useful to add a section in the README about how to force it to recompile for a different architecture, or what directories need to be deleted to uninstall/rerun, as the first time I recompiled didn't work as some pre-existing files were not overwritten.
